### ISSUE TITLE
88 on Accessibility 

### ISSUE THREAD

**Issue by mkatenolan** [fac-17/BGIP#31]
88 on accessibility - the messages aren't very helpful but I image just increasing the font will help that 👍 

![Screenshot 2019-08-23 at 10 32 01](https://user-images.githubusercontent.com/45820111/63582808-acb53f80-c591-11e9-9114-6d4fcaa636cc.png)

**Comment by reubengt** [comment]
ah we have an empty image tag for our logo which we never filled in. removing this should fix this
